trigger:
  branches:
    include:
      - main

pool:
  name: 'COMP367-WINDOWS'

jobs:
- job: Build
  steps:
  - script: |
      echo "Building your application"
    displayName: 'Build Step'

  - task: UseDotNet@2
    inputs:
    packageType: 'sdk'
    version: 'LTS'  # or 'latest'


  - script: |
      dotnet restore
      dotnet build --configuration Release
    displayName: 'Build and Restore'