trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'COMP367-WINDOWS'

jobs:
- job: Build
  steps:
  - script: |
      echo "Building your application"
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x.x'  # Specify the version of .NET SDK you need

  - script: |
      dotnet restore
      dotnet build --configuration Release
